D = AmigaOS4
CC = vc +aosppc
COPTS = -O1 -Iinclude -D__USE_INLINE__ -D__USE_OLD_TIMEVAL__
DO_CC = $(CC) $(COPTS) -o $@ -c $<

include mk.files


all: $D/libposix.a

$D/libposix.a: $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(OBJS5) $(OBJS6) $(OBJS7)
	delete force quiet $@
	ar q $@ $(OBJS1)
	ar q $@ $(OBJS2)
	ar q $@ $(OBJS3)
	ar q $@ $(OBJS4)
	ar q $@ $(OBJS5)
	ar q $@ $(OBJS6)
	ar q $@ $(OBJS7)

include mk.deps
